# =======================================================================================================================
# Site requirements
# 1.单独页:首页、关于、联系、版权、友链、404、置顶、类型、标签、时间、搜索
# 2.小工具:搜索、打赏、音乐、统计、特效
# 3.布局页:侧栏、头部、尾部、主体、导航
# =======================================================================================================================
# site dir list
# =======================================================================================================================
# .
# ├── .github
# |   ├── workflows
# |   |   ├── action.yml
# ├── _collections
# ├── _data
# ├── _drafts
# |   ├── 2022-01-31-olib-04.md
# |   └── 2022-01-31-olib-05.md
# ├── _includes
# |   ├── footer.html
# |   └── header.html
# ├── _layouts
# |   ├── category.html
# |   └── default.html
# |   ├── index.html
# |   └── page.html
# |   ├── post.html
# |   └── search.html
# |   ├── tags.html
# ├── _plugins
# ├── _posts
# |   ├── 2022-01-31-olib-01.md
# |   └── 2022-01-31-olib-02.md
# |   └── 2022-01-31-olib-03.md
# ├── _sass
# |   ├── hydeout
# |   └── hydeout.css
# ├── assets
# |   ├── css
# |   └── images
# |   └── css
# |   └── images
# |   └── js.html
# |   └── svg.html
# |   └── xml.html
# ├── pages
# |   ├── 404.md
# |   └── about.md
# |   └── category.md
# |   └── contact.html
# |   └── copyright.html
# |   └── link.html
# |   └── music.html
# |   └── nRFx-Doc.html
# |   └── nRFx-Guides.html
# |   └── nRFx-QA.html
# |   └── reward.html
# |   └── script.html
# |   └── search.html
# |   └── stat.html
# |   └── tags.html
# |   └── tline.html
# ├── _assets
# ├── _config.yml
# ├── .gitignore
# └── .stylelintrc.json
# └── CNAME
# └── favicon.ico
# ├── Gemfile
# └── index.html
# └── LICENSE.md
# └── olib.gemspec
# └── README.md

#左侧导航栏宽度修改：_variables.scss文件 $sidebar-width: 19rem !default;
#右侧文本显示宽度修改：_layout.scss文件 max-width: 100%;
# =======================================================================================================================
# site default config
# =======================================================================================================================
# Dependencies
language: zh-CN
timezone: Asia/Shanghai

# # 内容过滤
# show_drafts: null
# limit_posts: 0
# future:      true
# unpublished: false


# 语法高亮
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]


# 文章置顶

# 文章打赏
user:
  reward_comment: 坚持原创技术分享，您的支持将鼓励我继续创作！
  wechatpay:      '/assets/images/home/wechatpay_cfg_1.jpg'
  alipay:         '/assets/images/home/alipay_cfg_1.jpg'

# Setup
title:            OLIB
tagline:          '元仓库'
keywords:         OLIB,BLE,Nordic,nRF52,nRF53,nRF91,Zephyr,NCS
description:      '<a href="/contact.html" target="_blank">QQ群：542294007</a>'

author:
  name:           'Peter.Min'
  url:            https://www.olib.cn

cloud_pan: 
      url:        https://pan.olib.cn

github:
  repo:           https://github.com/em78p153s/olib
  

url:              https://www.olib.cn
baseurl:          ''
# permalink:        /blog/:title/
paginate:         10

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
